### ISSUE TITLE
app crashes 

### ISSUE THREAD

**Issue by amitkpandey** [SheikhZayed/News-Daily-Android-App#2]
when trying to open the app it crashes same happens for both the debug and release build

**Comment by rupak-samant-hike** [comment]
i have not been maintaining it for a long time,perhaps u could send me a crash log,so that i can help to fix

**Comment by SheikhZayed** [comment]
i have not been maintaining it for a long time,perhaps u could send me a crash log,so that i can help to fix

**Comment by amitkpandey** [comment]
here is the logcat when the app crashes

ActivityManager: Start proc 26392:me.ashif.newsapp/u0a151 for activity me.ashif.newsapp/.MainActivity
AndroidRuntime: FATAL EXCEPTION: main
AndroidRuntime: Process: me.ashif.newsapp, PID: 26392
AndroidRuntime: java.lang.RuntimeException: Unable to create application me.ashif.newsapp.app.AppController: java.lang.RuntimeException: java.net.MalformedURLException
AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4556)
AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:740)
AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(<Xposed>)
AndroidRuntime: 	at android.app.ActivityThread.access$1500(ActivityThread.java:151)
AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
AndroidRuntime: 	at android.os.Looper.loop(Looper.java:135)
AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5254)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
AndroidRuntime: 	at java.lang.reflect.Method.invoke(Method.java:372)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:902)
AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:697)
AndroidRuntime: 	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
AndroidRuntime: Caused by: java.lang.RuntimeException: java.net.MalformedURLException
AndroidRuntime: 	at com.parse.Parse.initialize(Parse.java:377)
AndroidRuntime: 	at com.parse.Parse.initialize(Parse.java:355)
AndroidRuntime: 	at me.ashif.newsapp.app.AppController.onCreate(AppController.java:31)
AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4553)
AndroidRuntime: 	... 13 more
AndroidRuntime: Caused by: java.net.MalformedURLException
AndroidRuntime: 	at java.net.URL.<init>(URL.java:152)
AndroidRuntime: 	at java.net.URL.<init>(URL.java:125)
 AndroidRuntime: 	at com.parse.Parse.initialize(Parse.java:375)
AndroidRuntime: 	... 17 more

**Comment by SheikhZayed** [comment]
the problems seems to be something related to Parse SDK,as you may be knowing that Parse has completely shutdown their services months back which may be creating the issue.I have used Parse in the app for analytics and Notifications.

Sorry .. you may consider removing Parse dependencies or move to firebase
